### ISSUE TITLE
Sign the windows bundle

### ISSUE THREAD

**Issue by pfrazee** [beakerbrowser/beaker#1715]
People downloading on windows get the "Not Trusted" warning. We need to buy a cert and sign on windows.

**Comment by rzelnik** [comment]
Could this be fixed by releasing the Windows version of Beaker through Microsoft's App Store?

**Comment by pfrazee** [comment]
We got the windows bundle signed, so you may still see _some_ alerts but over time it will decrease.
