### ISSUE TITLE
starting the browser without a network connection creates an Uncaught Exception

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#323]
Operation System: ubuntu 16.10
Beaker Version: latest master 0.6.1

To reproduce: 

 - Disable all network connections
 - Start the browser

throws: 

```
Uncaught Exception:
Error: addMembership ENODEV
    at exports._errnoException (util.js:1022:11)
    at Socket.addMembership (dgram.js:505:11)
    at Socket.<anonymous> (/home/mario/git/beaker/app/node_modules/multicast-dns/index.js:52:14)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at startListening (dgram.js:118:10)
    at dgram.js:225:7
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by pfrazee** [comment]
Solved with https://github.com/mafintosh/multicast-dns/pull/34. Pull latest deps so you have multicast-dns@6.1.1 and you should be good to go

**Comment by pmario** [comment]
Hi, that still throws a low level OS error message. ... What I'd like to see in the browser starts in "offline" mode and lets the user know. 

 - It is possible to open `file://` URIs eg: index.html
    - But the message makes a user think the browser is broken. But there is just no internet connection. 

 - Shouldn't it be possible to access locally saved dat repos?

**Comment by pfrazee** [comment]
What error is thrown?

**Comment by pmario** [comment]
The exact same info as above. 

app `npm list` shows this:

```
mario@mario-XPS-13-9350:~/git/beaker/app$ npm list | grep -i multi
│ ├── multibase@0.2.0
│ ├─┬ multicodec@0.1.0
│ └── multihashes@0.2.2
│ │   ├── multicast-dns@6.1.1
│ │ └─┬ multihashing-async@0.4.3
│ │   ├─┬ multihashes@0.4.3
│ │ │ ├─┬ multibase@0.3.1
│ │ │ └─┬ multicodec@0.1.5
│ ├─┬ multiaddr@2.2.1
│ ├─┬ multipart-stream@2.0.1
│ └── multihashes@0.2.2
├── multicb@1.2.1
├─┬ multihashes@0.3.3
│ └── multihashes@0.2.2
´´´
So I'm using multicast dns latest version

**Comment by pmario** [comment]
I can make a video if needed.

**Comment by pfrazee** [comment]
Ah ok, it's possible that the consumer of multicast-dns isn't

**Comment by pfrazee** [comment]
Continuing the discussion in https://github.com/maxogden/discovery-channel/issues/14
