### ISSUE TITLE
Setting Beaker as default browser on Linux fails

### ISSUE THREAD

**Issue by theorangepotato** [beakerbrowser/beaker#915]
Operation System: Debian 9 (Stretch)
Beaker version: Beaker 0.8.0-prerelease.3

In the intro screen, as well as in the settings, I can ostensibly set Beaker to be the default browser for dat:// or http:// urls; however, this setting does not currently seem to be saved, as if I change windows, it is reset as false. I do not know if this is because Beaker does not know how to handle such a setting on Linux and is silently failing, or if the change is merely not being written to a config file anywhere.

![defaultsettings](https://user-images.githubusercontent.com/15709902/37881857-41f53fb8-3052-11e8-926a-22a6f52b159a.gif)

**Comment by pfrazee** [comment]
Thanks, yeah I had this on my todo list. Will look into it.

**Comment by theorangepotato** [comment]
Glad to hear it! Let me know if I can be of any more help.

**Comment by pfrazee** [comment]
Looks like there may have been some problems with the `xdb-settings` script. Wasn't able to handle an input that you couldn't `which`, which beaker can't because we install via AppImage in userland. I solved it by invoking `xdb-mime` directly, but we'll see if that ends up being too brittle. Fingers crossed.

**Comment by Khoramyar** [comment]
Well, the issue is my Beaker browser does not show settings panel at all. What to delete in which path to reset the browser manually?

![image](https://user-images.githubusercontent.com/12546320/44996476-63e33000-afa8-11e8-82eb-8da4a5424592.png)

**Comment by Khoramyar** [comment]
Just FYI @pfrazee for debugging: console shows:

![image](https://user-images.githubusercontent.com/12546320/44996585-f4ba0b80-afa8-11e8-8cf7-5eae3777c3d3.png)

**Comment by pfrazee** [comment]
@Khoramyar that issue was solved by https://github.com/beakerbrowser/beaker/pull/1103 which is in master but hasnt been released yet. We'll package a new prerelease soon.

**Comment by SreeChandan** [comment]
OS: Manjaro
Version : 0.8.8 AppImage
@pfrazee has this issue been solved yet? I still have this problem. Actually it's the reverse of what @theorangepotato had. In my setting both 'dat://' and 'http://' are set as default. And I cant turn them off.

**Comment by pfrazee** [comment]
@SreeChandan That sounds like a new issue. I'm really short on time, so you might need to dig into the source yourself. Too many linux distros.

**Comment by Butterfly** [comment]
Good morning! Am just regurgitating a new command coincidentally encountered over at Debian-User a couple days ago:

`update-alternatives`

If you haven't done so already, try searching on that, and see if there's anything that can be manually tweaked. **DISCLAIMER:** That's Debian. It may be labeled something else system "default" related in other operating systems.

Am rereading the above comments one more time before submitting my own. I don't know if `/etc/alternatives` (in Debian, anyway) handles very specific details, e.g. dat and http, as each, their own entry versus all things Internet lumped as one. If things are only lumped as a single all-or-nothing CHOICE, maybe there's room for developing single steps as an... alternative... user-friendly option.

If this is new to anyone and you test drive it, **PLEASE** approach carefully. It would be really easy to mess things up with that command. I ran it wide open the other day so that it displays everything. I was uncomfortable with it because it seemed to *potentially* pick CHOICE 1 as a default when you work repetitively down an extensive list of CHOICES. As the old saying goes.. YM(hopefully)MV. :smile:
